num1=1
num2=0



try:
    x=num1/num2
    
except:
    print("error en el programa")

print("prorama de try")